CREATE TABLE TBL_LIBROS (
ID NUMERIC(6) PRIMARY KEY,
TITULO VARCHAR2(100) NOT NULL,
AUTOR VARCHAR2(100) NOT NULL,
GENERO VARCHAR2(50),
PRECIO NUMBER(6,2) NOT NULL,
STOCK NUMBER(3) NOT NULL,
ANIO_PUBLICACION NUMBER(4)
);

CREATE SEQUENCE SEQ_LIBROS START WITH 1 INCREMENT BY 1;

INSERT INTO TBL_LIBROS (ID, TITULO, AUTOR, GENERO, PRECIO, STOCK, ANIO_PUBLICACION)
VALUES (SEQ_LIBROS.NEXTVAL, 'El Principito', 'Antoine de Saint-Exupéry', 'Fantasía', 12.99, 10, 1943);
